name: Deploy My Static Site to Walrus with Provenance

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Upload Move Bytecode
        uses: zktx-io/sui-mvr-provenance@v0.0.1
        with:
          move-directory: ./hello_world